### ISSUE TITLE
Design layout. Due 24/04/2019

### ISSUE THREAD

**Issue by DuchSamai** [pnc-virtual-company/2019-Karthanea-Insurance-Company#11]
Design menu of the application

**Comment by BunsinNANH** [comment]
![error](https://user-images.githubusercontent.com/44716987/56552946-06433880-65b7-11e9-8a35-455f49fb87f8.PNG)

**Comment by BunsinNANH** [comment]
Problem with ingore file

**Comment by DuchSamai** [comment]
Dear friend I cannot pull data from the application.

![image](https://user-images.githubusercontent.com/44771497/56569950-2e955c00-65e4-11e9-8fa9-17d1fd721012.png)
