### ISSUE TITLE
Design logo and icon for the application

### ISSUE THREAD

**Issue by DuchSamai** [pnc-virtual-company/2019-Karthanea-Insurance-Company#4]
Design logo and icon for the application.Due  24/04/2019.

**Comment by ChendaCambodia** [comment]
This is logo that I have designed with icon
![logo-1](https://user-images.githubusercontent.com/45068083/56547892-de4cd880-65a8-11e9-8df3-5f364171fb33.png)
![icon-1](https://user-images.githubusercontent.com/45068083/56547894-dee56f00-65a8-11e9-9d56-ba1bfb8b4b16.png)

**Comment by ChendaCambodia** [comment]
And this one more logo with an icon
![icon-2](https://user-images.githubusercontent.com/45068083/56547994-1b18cf80-65a9-11e9-8a18-fb9155f8b21b.png)
![logo-2](https://user-images.githubusercontent.com/45068083/56547995-1b18cf80-65a9-11e9-9c8e-674ab22be6a2.png)

**Comment by kayroeuy** [comment]
This is my logo 
![logo-vc2](https://user-images.githubusercontent.com/44717936/56550393-b7de6b80-65af-11e9-8bce-cda76e3f0be4.png)
![logo-](https://user-images.githubusercontent.com/44717936/56550401-bc0a8900-65af-11e9-9dbc-6aa3deee1bf9.png)

**Comment by DuchSamai** [comment]
This is my logo
![samai_logo1](https://user-images.githubusercontent.com/44771497/56550222-41416e00-65af-11e9-9f0a-16ff0f13b3ec.png)

**Comment by ChhemSreynech** [comment]
This is my logo
![logo2](https://user-images.githubusercontent.com/44717755/56550377-abf2a980-65af-11e9-8686-9183ce998a74.png)
